CREATE TABLE pintest (a int);
INSERT INTO pintest VALUES (1);
INSERT INTO pintest VALUES (2);
INSERT INTO pintest VALUES (3);
INSERT INTO pintest VALUES (4);
SELECT * FROM pintest;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY;
PIN;
SELECT * from pintest;
COMMIT;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY;
PIN;
SELECT * from pintest;
COMMIT;

DELETE FROM pintest WHERE a=4;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY;
PIN;
SELECT * from pintest;
COMMIT;

\set QUIET off

INSERT INTO pintest VALUES (5);
SELECT * from pintest;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY SNAPSHOTID 5;
SELECT * from pintest;
COMMIT;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY SNAPSHOTID 6;
SELECT * from pintest;
COMMIT;

-- vacuum shouldn't change anything
VACUUM;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY SNAPSHOTID 5;
SELECT * from pintest;
COMMIT;

BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY SNAPSHOTID 6;
SELECT * from pintest;
COMMIT;

\set QUIET on

UNPIN 5;
BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY SNAPSHOTID 5;

DROP TABLE pintest;