SELECT avg(id) FROM categories;
SELECT avg(id) FROM regions;
SELECT avg(id) FROM users;
SELECT avg(id) FROM items;
SELECT avg(id) FROM old_items;
SELECT avg(id) FROM bids;
SELECT avg(id) FROM comments;
SELECT avg(id) FROM buy_now;
SELECT avg(id) FROM ids;
